/** Сырые поля строки для кэша / baseRows — без вычисленных значений калькулятора. */
export function slimRowForCache(row) {
  return {
    nmId: row.nmId,
    vendorCode: row.vendorCode,
    brand: row.brand,
    title: row.title,
    subjectId: row.subjectId,
    subjectName: row.subjectName,
    skus: row.skus || [],
    stockFbo: row.stockFbo,
    stockFbs: row.stockFbs,
    orders7d: row.orders7d,
    purchasePrice: row.purchasePrice,
    salePrice: row.salePrice,
    basePrice: row.basePrice,
    ourPrice: row.ourPrice,
    lengthCm: row.lengthCm,
    widthCm: row.widthCm,
    heightCm: row.heightCm,
    fboCategoryRate: row.fboCategoryRate,
    fboCommission: row.fboCommission ?? row.fboCategoryRate,
    fbsCommission: row.fbsCommission,
    buyoutRate: row.buyoutRate,
    buyoutRateFbs: row.buyoutRateFbs,
    buyoutRateFbo: row.buyoutRateFbo,
    acquiringRate: row.acquiringRate,
    actualAcquiringRub: row.actualAcquiringRub,
    retailPricePerUnit: row.retailPricePerUnit,
    actualStorageRub: row.actualStorageRub,
    actualAcceptanceRub: row.actualAcceptanceRub,
    actualProcessingRub: row.actualProcessingRub,
    advertisingDrr: row.advertisingDrr,
    actualLogisticsRub: row.actualLogisticsRub,
    actualLogisticsRubFbs: row.actualLogisticsRubFbs,
    actualLogisticsRubFbo: row.actualLogisticsRubFbo,
    actualLogisticsRubAll: row.actualLogisticsRubAll,
    actualForwardLogisticsRub: row.actualForwardLogisticsRub,
    actualReturnLogisticsRub: row.actualReturnLogisticsRub,
    actualForwardLogisticsRubFbs: row.actualForwardLogisticsRubFbs,
    actualReturnLogisticsRubFbs: row.actualReturnLogisticsRubFbs,
    reportForwardLogistics: row.reportForwardLogistics,
    reportReturnLogistics: row.reportReturnLogistics,
    reportOtherLogistics: row.reportOtherLogistics,
    reportForwardLogisticsFbs: row.reportForwardLogisticsFbs,
    reportReturnLogisticsFbs: row.reportReturnLogisticsFbs,
    reportSales: row.reportSales,
    reportSalesFbs: row.reportSalesFbs,
    reportSalesFbo: row.reportSalesFbo,
    reportReturns: row.reportReturns,
    reportRetailSum: row.reportRetailSum,
    reportRetailReturnSum: row.reportRetailReturnSum,
    reportForPayNet: row.reportForPayNet,
    reportCommissionRub: row.reportCommissionRub,
    reportAcquiringRub: row.reportAcquiringRub,
    reportLogisticsRub: row.reportLogisticsRub,
    reportStorageRub: row.reportStorageRub,
    reportAcceptanceRub: row.reportAcceptanceRub,
    reportProcessingRub: row.reportProcessingRub,
    reportPenaltyRub: row.reportPenaltyRub,
    reportDeductionRub: row.reportDeductionRub,
    reportAdditionalPaymentRub: row.reportAdditionalPaymentRub,
    adSpend: row.adSpend,
    fbsAvgDeliveryHours: row.fbsAvgDeliveryHours,
    fboWarehouseName: row.fboWarehouseName,
    fbsWarehouseName: row.fbsWarehouseName,
    warehouseCoeff: row.warehouseCoeff,
    storageBasePerLiter: row.storageBasePerLiter,
    storageAdditionalPerLiter: row.storageAdditionalPerLiter,
    storageCoeff: row.storageCoeff,
    fbsCoeff: row.fbsCoeff,
  };
}

export function slimRowsForCache(rows) {
  return (rows || []).map(slimRowForCache);
}
